#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Usage: rbt <menuentry> <--editonly> <-e>"
    echo "Use --editonly or -e to edit the grub entry without rebooting."
    exit 1
fi

ENTRY=$(awk -F\' '/menuentry / {print $2}' /boot/grub/grub.cfg  | awk -v pattern="^$1.*" '$0 ~ pattern { print $0; exit}')
echo "Selected entry: $ENTRY"

if [ -z "${ENTRY}" ]; then
    echo "No matching entry found."
    exit 1
fi
ESCAPED_ENTRY=$(printf '%s\n' "$ENTRY" | sed -e 's/[\/&]/\\&/g')

sed -i "s/GRUB_DEFAULT=.*/GRUB_DEFAULT='$ESCAPED_ENTRY'/" /etc/default/grub

if [ $? -eq 0 ]; then
    echo "Grub configuration updated successfully."
else
    echo "Failed to update grub configuration."
    exit 1
fi

update-grub

if [[ \ $*\  == *\ --editonly\ * ]] || [[ \ $*\  == *\ -e\ * ]]; then
    echo "Edit only mode, no reboot. Use without flag to reboot."
else
    echo "Rebooting..."
    reboot
fi